export const CREATE_DRAFT_SUCCESS = 'CREATE_DRAFT_SUCCESS';
export const CREATE_DRAFT_ERROR = 'CREATE_DRAFT_ERROR';
export const CREATE_ARTICLE_BEGIN = 'CREATE_ARTICLE_BEGIN';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
