export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const AUTHORS_LOADED = 'AUTHORS_LOADED';
export const SET_KEYWORD = 'SET_KEYWORD';
