export const SOCIAL_AUTH_BEGIN = 'SOCIAL_AUTH_BEGIN';
export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';
export const SOCIAL_AUTH_FAILURE = 'SOCIAL_AUTH_FAILURE';
export const SOCIALMEDIA_PROVIDER = 'SOCIALMEDIA_PROVIDER';
